CREATE TABLE products
(
	ID SERIAL,
	NAME TEXT CONSTRAINT prodchk CHECK(char_length(NAME) >= 3)
);

CREATE TABLE users
(
	ID SERIAL,
	USERNAME TEXT NOT NULL CONSTRAINT lengthchk CHECK(char_length(USERNAME) >= 4),
	PASSWORD TEXT NOT NULL,
	ROLE TEXT NOT NULL
);

INSERT INTO products (NAME) VALUES('Hose');
INSERT INTO products (NAME) VALUES('Schuhe');
